version: "3.9"

services:
  gateway:
    image: EcosystemName/gateway:dev
    ports:
      - "8080:8080"

  user-service:
    image: EcosystemName/user-service:dev

  order-service:
    image: EcosystemName/order-service:dev

  payment-service:
    image: EcosystemName/payment-service:dev

  notification-service:
    image: EcosystemName/notification-service:dev
