version: "3.9"

services:
  gateway:
    image: ecosystemname/gateway:dev
    ports:
      - "8080:8080"

  user-service:
    image: ecosystemname/user-service:dev

  order-service:
    image: ecosystemname/order-service:dev

  payment-service:
    image: ecosystemname/payment-service:dev

  notification-service:
    image: ecosystemname/notification-service:dev
